### ISSUE TITLE
Still supported?

### ISSUE THREAD

**Issue by caraya** [felixzapata/gulp-axe-core#4]
If the project is no longer supported I'd suggest putting the notice somewhere in the repo main page :)

**Comment by felixzapata** [comment]
hi @caraya , this repo is still supported in case of, but maybe you should take a look to [gulp-axe-webdriver](https://github.com/felixzapata/gulp-axe-webdriver).

**Comment by caraya** [comment]
I saw the pointer and I'm using that. Thanks
